name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Create kubeconfig
      run: |
        mkdir -p ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config

    - name: Use context
      run: kubectl config use-context minikube

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8/deployment.yaml
        kubectl apply -f k8/service.yaml
