name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

#cd part
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          repository: ${{ github.repository }}
    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
      with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.26.0'
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Deploy to Kubernetes
      run: |
        kubectl create namespace wisecow
        kubectl apply -f k8/deployment.yaml -n  wisecow
        kubectl apply -f k8/service.yaml -n wisecow
        kubectl get pods -n wisecow
        sleep 200 #for pods waitinh time
        kubectl get pods -n wisecow
        kubectl get service -n wisecow
        kubectl port-forward svc/wisecow-service 8080:80 -n wisecow
        curl http://localhost:8080
