name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.26.0'
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Deploy to Kubernetes
        run: |
            ls -al
            pwd
            kubectl apply -f k8/deployment.yaml
            kubectl apply -f k8/service.yaml
            kubectl get pods -A
