name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set IMAGE_NAME and TIMESTAMP
      id: vars
      run: |
        echo "IMAGE_NAME=akhilyechuri064/wisecow" >> $GITHUB_ENV
        echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
    - name: Build and push
      run: |
        docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }}
        docker tag ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }} ${{ env.IMAGE_NAME }}:v${{ github.run_number }}
        docker tag ${{ env.IMAGE_NAME }}:${{ env.TIMESTAMP }} ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:v${{ github.run_number }}
        docker push ${{ env.IMAGE_NAME }}:latest
        echo "let's see images"
        docker images

#cd part
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          repository: ${{ github.repository }}
    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
      with:
          minikube-version: 'latest'
          kubernetes-version: 'v1.26.0'
    - name: Try the cluster!
      run: kubectl get pods -A
    - name: Deploy to Kubernetes
      run: |
        kubectl create namespace wisecow
        kubectl apply -f k8/deployment.yaml -n  wisecow
        kubectl apply -f k8/service.yaml -n wisecow
        kubectl get pods -n wisecow
        sleep 200 #for pods waitinh time
        kubectl get pods -n wisecow
        kubectl get service -n wisecow
        kubectl get nodes -o wide 
    - name: Setup Kubernetes port-forward daemon
      uses: vbem/k8s-port-forward@v1
      with:
        workload: 'svc/wisecow-service'
        port: '4450:80'
        namespace: 'wisecow'

    - name: Test Application
      run: |
        curl http://localhost:4450 || (echo "Curl failed; check application status." && exit 1)
